package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/AlreadyAttachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The attachTo or attachToNew request failed because this SEAccessInterface
 * is already attached to an SE.
 */
public final class AlreadyAttachedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public AlreadyAttachedException ()
  {
    super(AlreadyAttachedExceptionHelper.id());
  } // ctor

  public AlreadyAttachedException (String _nlsText, String _wideNlsText)
  {
    super(AlreadyAttachedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public AlreadyAttachedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(AlreadyAttachedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class AlreadyAttachedException
