package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/BadIndicesException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The supplied indices are not valid for the element type.  This does not mean
 * that the SE does not exist.  Rather that the indices are not valid for an
 * element of the specified type.
 */
public final class BadIndicesException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public BadIndicesException ()
  {
    super(BadIndicesExceptionHelper.id());
  } // ctor

  public BadIndicesException (String _nlsText, String _wideNlsText)
  {
    super(BadIndicesExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public BadIndicesException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(BadIndicesExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class BadIndicesException
