package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/BadIndicesExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The supplied indices are not valid for the element type.  This does not mean
 * that the SE does not exist.  Rather that the indices are not valid for an
 * element of the specified type.
 */
public final class BadIndicesExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.BadIndicesException value = null;

  public BadIndicesExceptionHolder ()
  {
  }

  public BadIndicesExceptionHolder (com.Metaswitch.MVS.Corba.BadIndicesException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.BadIndicesExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.BadIndicesExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.BadIndicesExceptionHelper.type ();
  }

}
