package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ClientSessionManagerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionManagerInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/


/**
 * The ClientSessionManagerInterface is the initial interface used by all
 * client applications to establish communications with the EMS server.
 */
public interface ClientSessionManagerInterface extends ClientSessionManagerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  /**
     * User types for use on the applicationLogin method.  See the "MetaSwitch
     * Class 5 Softswitch: Operations Manual" chapter on "User Security" for more
     * details on User types.
     */
  public static final int USER_TYPE_SUBSCRIBER = (int)(1);
  public static final int USER_TYPE_SUPPORT_AGENT = (int)(2);
  public static final int USER_TYPE_SUPERVISOR = (int)(3);
  public static final int USER_TYPE_NET_ADMIN = (int)(4);
  public static final int USER_TYPE_DCL_ENGINEER = (int)(5);
  public static final int USER_TYPE_SYS_ADMIN = (int)(6);
  public static final int USER_TYPE_SUPER_USER = (int)(7);
  public static final int USER_TYPE_CALEA_USER = (int)(8);
  public static final int USER_TYPE_CALEA_DCL_ENG = (int)(9);
  public static final int USER_TYPE_WKFLOW_USER_A = (int)(10);
  public static final int USER_TYPE_WKFLOW_USER_B = (int)(11);
  public static final int USER_TYPE_WKFLOW_USER_C = (int)(12);

  /**
     * Version identifiers for use on the userLogin and applicationLogin methods.
     * These constants define all of the versions that are supported by the
     * current release of the EMS.
     */
  public static final int VERSION_1_04 = (int)(0x01040000);
  public static final int VERSION_2_0 = (int)(0x02000000);
  public static final int VERSION_2_1 = (int)(0x02010000);
  public static final int VERSION_2_2 = (int)(0x02020000);
  public static final int VERSION_2_3 = (int)(0x02030000);
  public static final int VERSION_2_3_01 = (int)(0x02030100);
  public static final int VERSION_3_0 = (int)(0x03000000);
  public static final int VERSION_3_0_01 = (int)(0x03000100);
  public static final int VERSION_3_0_02 = (int)(0x03000200);
  public static final int VERSION_3_0_03 = (int)(0x03000300);
  public static final int VERSION_3_1 = (int)(0x03010000);
  public static final int VERSION_3_1_01 = (int)(0x03010100);
  public static final int VERSION_3_2 = (int)(0x03020000);
  public static final int VERSION_4_0 = (int)(0x04000000);
  public static final int VERSION_4_0_01 = (int)(0x04000100);
  public static final int VERSION_4_1 = (int)(0x04010000);
  public static final int VERSION_4_1_01 = (int)(0x04010100);
  public static final int VERSION_4_1_02 = (int)(0x04010200);
  public static final int VERSION_4_2 = (int)(0x04020000);
  public static final int VERSION_5_0 = (int)(0x05000000);
  public static final int VERSION_5_0_02 = (int)(0x05000200);
  public static final int VERSION_5_1 = (int)(0x05010000);
  public static final int VERSION_6_0 = (int)(0x06000000);
  public static final int VERSION_6_1 = (int)(0x06010000);
  public static final int VERSION_7_0 = (int)(0x07000000);
  public static final int VERSION_7_0_01 = (int)(0x07000100);
  public static final int VERSION_7_1 = (int)(0x07010000);
  public static final int VERSION_7_1_01 = (int)(0x07010100);
  public static final int VERSION_7_2 = (int)(0x07020000);
  public static final int VERSION_7_3 = (int)(0x07030000);
  public static final int VERSION_7_3_01 = (int)(0x07030100);
  public static final int VERSION_7_4 = (int)(0x07040000);
  public static final int VERSION_7_4_01 = (int)(0x07040100);
  public static final int VERSION_8_0 = (int)(0x08000000);
  public static final int VERSION_8_0_02 = (int)(0x08000200);
  public static final int VERSION_8_0_03 = (int)(0x08000300);
  public static final int VERSION_8_1 = (int)(0x08010000);
  public static final int VERSION_8_1_01 = (int)(0x08010100);
  public static final int VERSION_8_1_02 = (int)(0x08010200);
  public static final int VERSION_8_2 = (int)(0x08020000);
  public static final int VERSION_8_2_02 = (int)(0x08020200);
  public static final int VERSION_8_3 = (int)(0x08030000);
  public static final int VERSION_8_3_01 = (int)(0x08030100);
  public static final int VERSION_8_3_03 = (int)(0x08030300);
  public static final int VERSION_8_3_04 = (int)(0x08030400);
  public static final int VERSION_8_3_10 = (int)(0x08030A00);
  public static final int VERSION_9_0 = (int)(0x09000000);
  public static final int VERSION_9_0_01 = (int)(0x09000100);
  public static final int VERSION_9_0_02 = (int)(0x09000200);
  public static final int VERSION_9_0_03 = (int)(0x09000300);
  public static final int VERSION_9_0_10 = (int)(0x09000A00);
  public static final int VERSION_9_1 = (int)(0x09010000);
  public static final int VERSION_9_1_10 = (int)(0x09010A00);
  public static final int VERSION_9_1_15 = (int)(0x09010F00);
  public static final int VERSION_9_2 = (int)(0x09020000);
  public static final int VERSION_9_2_01 = (int)(0x09020100);
  public static final int VERSION_9_2_10 = (int)(0x09020A00);
  public static final int VERSION_9_2_11 = (int)(0x09020B00);
  public static final int VERSION_9_3 = (int)(0x09030000);
  public static final int VERSION_9_3_10 = (int)(0x09030A00);
  public static final int VERSION_9_3_20 = (int)(0x09031400);

  /**
     * Version identifiers for use on the userLogin_SessionController,
     * userLoginWithNewPassword_SessionController and
     * applicationLogin_SessionController methods. These constants define all of 
     * the versions that are supported by the current release of the Session
     * Controller (Perimeta).
     */
  public static final int VERSION_3_9_SC = (int)(0x03090000);
  public static final int VERSION_3_9_20_SC = (int)(0x03091400);
  public static final int VERSION_3_9_40_SC = (int)(0x03092800);
  public static final int VERSION_4_0_00_SC = (int)(0x04000000);
  public static final int VERSION_4_0_20_SC = (int)(0x04001400);
  public static final int VERSION_4_0_40_SC = (int)(0x04002800);
  public static final int VERSION_4_1_00_SC = (int)(0x04010000);
  public static final int VERSION_4_1_20_SC = (int)(0x04011400);
  public static final int VERSION_4_1_40_SC = (int)(0x04012800);
  public static final int VERSION_4_2_00_SC = (int)(0x04020000);
  public static final int VERSION_4_2_20_SC = (int)(0x04021400);
  public static final int VERSION_4_2_40_SC = (int)(0x04022800);
} // interface ClientSessionManagerInterface
