package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ClientSessionManagerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionManagerInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/


/**
 * The ClientSessionManagerInterface is the initial interface used by all
 * client applications to establish communications with the EMS server.
 */
abstract public class ClientSessionManagerInterfaceHelper
{
  private static String  _id = "IDL:ClientSessionManagerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.ClientSessionManagerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionManagerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.Metaswitch.MVS.Corba.ClientSessionManagerInterfaceHelper.id (), "ClientSessionManagerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionManagerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientSessionManagerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.ClientSessionManagerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionManagerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.ClientSessionManagerInterface)
      return (com.Metaswitch.MVS.Corba.ClientSessionManagerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._ClientSessionManagerInterfaceStub stub = new com.Metaswitch.MVS.Corba._ClientSessionManagerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionManagerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.ClientSessionManagerInterface)
      return (com.Metaswitch.MVS.Corba.ClientSessionManagerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._ClientSessionManagerInterfaceStub stub = new com.Metaswitch.MVS.Corba._ClientSessionManagerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
