package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ClientSessionInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/


/**
 * The ClientSessionInterface provides methods for managing the client's
 * session.  The session is terminated when one of the following occurs:
 * - the client application invokes the logout method;
 * - a fixed timeout period expires;
 * - another EMS user changes the details of the EMS user account associated
 * with this client session.
 */
public interface ClientSessionInterfaceOperations 
{

  /**
     * Queries the client's privileges on the EMS Server.  See the "MetaSwitch
     * Class 5 Softswitch: Operations Manual" for more details on User security
     * and privileges.
     *
     * @return The client's privileges.
     **/
  long getPrivileges ();

  /**
     * Provides a string that identifies this client session.  The string is
     * unique on this EMS Server and will not be repeated until the server is
     * restarted.
     *
     * @return  String identifier of this client session.
     **/
  String getSessionID ();

  /**
     * Terminates this client session.  This interface, and all interfaces
     * returned by it, are no longer valid and will throw exceptions if
     * methods are invoked on them.
     **/
  void logout ();

  /**
     * Client sessions expire after a fixed timeout period (returned by
     * getTimeoutPeriod).  This method resets the timer associated with this
     * session.
     *
     * @throws ElementOperationFailedException  If this method is called after
     * the client session has expired.
     **/
  void keepAlive () throws com.Metaswitch.MVS.Corba.ElementOperationFailedException;

  /**
     * Client sessions expire a fixed timeout period after the last call to the
     * keepAlive method.  This method returns the length of that timeout period.
     *
     * @return The timeout period in milliseconds.
     **/
  long getTimeoutPeriod ();

  /**
     * Obtains a reference to an SEAccessFactoryInterface that can be used to
     * obtain SEAccessInterface objects.
     *
     * @return  SEAccessFactoryInterface object reference.
     **/
  com.Metaswitch.MVS.Corba.SEAccessFactoryInterface getSEAccessFactory ();

  /**
     * Attempts to set the password of the EMS User account associated with
     * this client session.  This method can only be called if this client
     * session was returned from a userLogin; it cannot be called after an
     * applicationLogin.
     *
     * @param  String containing the new password. The password must be 6, 7,
     *         or 8 characters in length.
     *
     * @throws ElementUnavailableException      See SEExceptions.idl.
     * @throws ElementOperationFailedException  See SEExceptions.idl.
     * @throws FieldBadValueException  Thrown if the new password is not a
     *         valid string of 6, 7 or 8 characters in length.
     **/
  void setPassword (String newPassword) throws com.Metaswitch.MVS.Corba.ElementUnavailableException, com.Metaswitch.MVS.Corba.ElementOperationFailedException, com.Metaswitch.MVS.Corba.FieldBadValueException;

  /**
     * Associates this client session with a specific National Language Specific
     * locale.  If successful, all display strings are returned as human-readable
     * NLS-interpreted strings rather than non-readable NLS-enabled string.
     *
     * This method must be called before getSEAccessFactory.  This method should
     * not be called more than once.
     *
     * @param  The language parameter is a valid ISO Language Code. These codes
     *         are the lower-case two-letter codes as defined by ISO-639.
     * @param  The country parameter is a valid ISO Country Code. These codes are
     *         the upper-case two-letter codes as defined by ISO-3166.
     *
     * @throws FieldBadValueException  If the language or country parameters is
     *         not a recognized code.
     **/
  void setNLSLocale (String language, String country) throws com.Metaswitch.MVS.Corba.FieldBadValueException;

  /**
     * Indicates which specific National Language Specific locale is
     * associated with this client session.
     *
     * @param language  String holder that is returned with the ISO Language Code
     *                  of the set locale.  If setNLSLocale has not previously
     *                  been called, a zero-length string will be returned.
     * @param country  String holder that is returned with the ISO Country Code
     *                  of the set locale.  If setNLSLocale has not previously
     *                  been called, a zero-length string will be returned.
     **/
  void getNLSLocale (org.omg.CORBA.StringHolder language, org.omg.CORBA.StringHolder country);

  /**
     * Each invocation of createsSEAccess returns an identical, generic
     * SEAccessInterface instance; this instance only becomes associated with a
     * specific SE as a result of subsequent method invocations on the
     * SEAccessInterface.  The client application is obliged to call the destroy
     * method on the SEAccessInterface when it has finished using it.
     *
     * @return SEAccessInterface instance.
     *
     * @throws ElementOperationFailedException  If the request failed for any
     *   reason, for example if the EMS Server does not have enough memory to
     *   complete the request.  See SEExceptions.idl.
     */
  com.Metaswitch.MVS.Corba.SEAccessInterface createSEAccess () throws com.Metaswitch.MVS.Corba.ElementOperationFailedException;

  /**
     * Returns the time of the last successful login in UTC.
     *
     * This method is only valid on ClientSessions returned by userLogin or
     * userLoginWithNewPassword.  For ClientSessions returned by
     * applicationLogin, this method returns 0.
     *
     * @returns the time of last login in UTC
     */
  int getLastLogin ();

  /**
     * Returns information about the password, e.g. whether it expires or not.
     *
     * This method is only valid on ClientSessions returned by userLogin or
     * userLoginWithNewPassword.  For ClientSessions returned by
     * applicationLogin, this method returns PASSWORD_FLAG_NEVER_EXPRIES.
     *
     * @returns flags about the password.
     */
  int getPasswordFlags ();

  /**
     * If the password expires (see getPasswordFlags), returns the number of days
     * until the password expires.
     *
     * This method is only valid on ClientSessions returned by userLogin or
     * userLoginWithNewPassword.  For ClientSessions returned by
     * applicationLogin, this method returns 0.
     *
     * @returns days until the password expires
     */
  int getDaysToPasswordExpiry ();

  /**
     * The number of failed logins since the last successful login.
     *
     * This method is only valid on ClientSessions returned by userLogin or
     * userLoginWithNewPassword.  For ClientSessions returned by
     * applicationLogin, this method returns 0.
     *
     * @returns the number of failed logins since the last successful login.
     */
  int getFailedLogins ();

  /**
     * Any message associated with the login.  For instance, this may be a
     * message passed back from a RADIUS server, if that is configured.
     *
     * This method is only valid on ClientSessions returned by userLogin or
     * userLoginWithNewPassword.  For ClientSessions returned by
     * applicationLogin, this method returns 0.
     *
     * @returns a message to display to the user.
     */
  String getLoginMessage ();

  /**
     * Gets log information for a specific log from the EMS.  If the log
     * is not found, then a LogNotFoundException is thrown.  If the log is
     * found, text is returned as human-readable NLS-interpreted strings
     * rather than non-readable NLS-enabled string.
     *
     * @return   A LogInformation structure containing the log information
     *           requested.
     *
     * @param  metaSwitchUID  The unique identifier for the MetaSwitch on which
     *                        the log was raised.  The value to use is the
     *                        - "MetaSwitch unique identifier" in the MetaSwitch
     *                          element, for elements on the MetaSwitch
     *                        - "EMS unique identifier" in the EMS element, for
     *                          elements on the EMS.
     * @param  logCorrelator  The log correlator, which identifies the log on the
     *                        specified MetaSwitch.
     * @param  timeToWaitForLog
     *                        How long (in seconds) to wait for the log to be
     *                        found, if it is not instantly available.  May be
     *                        zero.
     *
     * @throws LogNotFoundException
     *                        If the log could not be found.
     */
  com.Metaswitch.MVS.Corba.LogInformation getLogInformation (String metaSwitchUID, long logCorrelator, int timeToWaitForLog) throws com.Metaswitch.MVS.Corba.LogNotFoundException;

  /**
     * Tells the log collector to get all logs from all log sources that have
     * been raised.  This method is used to obtain logs that the user knows have
     * been raised (e.g.  because there is a correlator value in an alarm log
     * correlator field) but have not yet been 'collected' as the timer that
     * governs this collection has not yet popped to indicate that log collection
     * should happen.  This method invokes the collection asynchronously so the
     * logs may still not be available immediately it returns but should be
     * shortly afterwards.
     *
     * @throws ElementOperationFailedException
     */
  void getLogs () throws com.Metaswitch.MVS.Corba.ElementOperationFailedException;

  /**
     * Get the details of the Cluster Site which has the Leader in it.
     *
     * @param ipAddress String holder that is returned with the IP address of
     *                  the leader site.
     *
     * @param siteName String holder that is returned with the name of the leader
     *                 site.
     *
     * @param siteID The ID of the leader site.
     */
  void getLeaderSiteMVS (org.omg.CORBA.StringHolder ipAddress, org.omg.CORBA.StringHolder siteName, org.omg.CORBA.IntHolder siteID) throws com.Metaswitch.MVS.Corba.ElementOperationFailedException;

  /**
    * Checks to see Session Controller (Perimeta) Management is enabled.
    *
    * @return Whether Session Controller (Perimeta) Management is enabled.
    */
  boolean isSessionControllerManagementEnabled ();
} // interface ClientSessionInterfaceOperations
