package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ClientSessionInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/


/**
 * The ClientSessionInterface provides methods for managing the client's
 * session.  The session is terminated when one of the following occurs:
 * - the client application invokes the logout method;
 * - a fixed timeout period expires;
 * - another EMS user changes the details of the EMS user account associated
 * with this client session.
 */
abstract public class ClientSessionInterfaceHelper
{
  private static String  _id = "IDL:ClientSessionInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.ClientSessionInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.Metaswitch.MVS.Corba.ClientSessionInterfaceHelper.id (), "ClientSessionInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientSessionInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.ClientSessionInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.ClientSessionInterface)
      return (com.Metaswitch.MVS.Corba.ClientSessionInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._ClientSessionInterfaceStub stub = new com.Metaswitch.MVS.Corba._ClientSessionInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.Metaswitch.MVS.Corba.ClientSessionInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.ClientSessionInterface)
      return (com.Metaswitch.MVS.Corba.ClientSessionInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._ClientSessionInterfaceStub stub = new com.Metaswitch.MVS.Corba._ClientSessionInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
