package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/CreationFailedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The request to create an SE by attachToNew failed.  The reason for the
 * failure will be detailed in the nlsText field.
 */
public final class CreationFailedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.CreationFailedException value = null;

  public CreationFailedExceptionHolder ()
  {
  }

  public CreationFailedExceptionHolder (com.Metaswitch.MVS.Corba.CreationFailedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.CreationFailedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.CreationFailedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.CreationFailedExceptionHelper.type ();
  }

}
