package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/DualStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SettingsUserInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/

public final class DualStringHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.DualString value = null;

  public DualStringHolder ()
  {
  }

  public DualStringHolder (com.Metaswitch.MVS.Corba.DualString initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.DualStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.DualStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.DualStringHelper.type ();
  }

}
