package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/DualString.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SettingsUserInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/

public final class DualString implements org.omg.CORBA.portable.IDLEntity
{
  public String internal = null;
  public String display = null;

  public DualString ()
  {
  } // ctor

  public DualString (String _internal, String _display)
  {
    internal = _internal;
    display = _display;
  } // ctor

} // class DualString
