package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ElementNotLockedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The unlock request failed because the SE is not locked by this user.
 */
public final class ElementNotLockedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.ElementNotLockedException value = null;

  public ElementNotLockedExceptionHolder ()
  {
  }

  public ElementNotLockedExceptionHolder (com.Metaswitch.MVS.Corba.ElementNotLockedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ElementNotLockedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ElementNotLockedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ElementNotLockedExceptionHelper.type ();
  }

}
