package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ElementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class ElementHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.Element value = null;

  public ElementHolder ()
  {
  }

  public ElementHolder (com.Metaswitch.MVS.Corba.Element initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ElementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ElementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ElementHelper.type ();
  }

}
