package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ElementChangedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The SE's state has been changed by another user since this user
 * last called getSnapshot.  This user must call getSnapshot, discarding any
 * outstanding changes made to their local SettingsUserInterface.
 */
public final class ElementChangedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public ElementChangedException ()
  {
    super(ElementChangedExceptionHelper.id());
  } // ctor

  public ElementChangedException (String _nlsText, String _wideNlsText)
  {
    super(ElementChangedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public ElementChangedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(ElementChangedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class ElementChangedException
