package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ElementUnavailableException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The request failed because the MetaSwitch, or the configuration on the
 * EMS Server, could not be accessed.  This may be because of a
 * communications failure between the EMS Server and the MetaSwitch; or
 * one of the systems may be starting up.
 *
 * See the comment at the top of this file for details on individual fields.
 */
public final class ElementUnavailableException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public int mainReturnCode = (int)0;
  public int subReturnCode = (int)0;
  public String erroredField = null;
  public long errorLogIndex = (long)0;
  public String errorNEName = null;
  public String neIdentifier = null;
  public String wideNlsText = null;

  public ElementUnavailableException ()
  {
    super(ElementUnavailableExceptionHelper.id());
  } // ctor

  public ElementUnavailableException (String _nlsText, int _mainReturnCode, int _subReturnCode, String _erroredField, long _errorLogIndex, String _errorNEName, String _neIdentifier, String _wideNlsText)
  {
    super(ElementUnavailableExceptionHelper.id());
    nlsText = _nlsText;
    mainReturnCode = _mainReturnCode;
    subReturnCode = _subReturnCode;
    erroredField = _erroredField;
    errorLogIndex = _errorLogIndex;
    errorNEName = _errorNEName;
    neIdentifier = _neIdentifier;
    wideNlsText = _wideNlsText;
  } // ctor


  public ElementUnavailableException (String $reason, String _nlsText, int _mainReturnCode, int _subReturnCode, String _erroredField, long _errorLogIndex, String _errorNEName, String _neIdentifier, String _wideNlsText)
  {
    super(ElementUnavailableExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    mainReturnCode = _mainReturnCode;
    subReturnCode = _subReturnCode;
    erroredField = _erroredField;
    errorLogIndex = _errorLogIndex;
    errorNEName = _errorNEName;
    neIdentifier = _neIdentifier;
    wideNlsText = _wideNlsText;
  } // ctor

} // class ElementUnavailableException
