package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ElementAlreadyLockedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The lock request failed because the SE is already locked by this user.
 */
public final class ElementAlreadyLockedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public ElementAlreadyLockedException ()
  {
    super(ElementAlreadyLockedExceptionHelper.id());
  } // ctor

  public ElementAlreadyLockedException (String _nlsText, String _wideNlsText)
  {
    super(ElementAlreadyLockedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public ElementAlreadyLockedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(ElementAlreadyLockedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class ElementAlreadyLockedException
