package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ElementOrderHintValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

abstract public class ElementOrderHintValueHelper
{
  private static String  _id = "IDL:ElementOrderHintValue:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.ElementOrderHintValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.ElementOrderHintValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.id (), "ElementOrderHintValue", new String[] { "stringNumber", "lexicographic", "alphabetic", "elementName", "reverseStringNumber", "orderOnSpecificField"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.ElementOrderHintValue read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.Metaswitch.MVS.Corba.ElementOrderHintValue.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.ElementOrderHintValue value)
  {
    ostream.write_long (value.value ());
  }

}
