package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ElementOperationFailedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * Thrown if the requested operation failed to complete successfully.
 * See the comment at the top of this file for details on individual fields.
 */
public final class ElementOperationFailedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.ElementOperationFailedException value = null;

  public ElementOperationFailedExceptionHolder ()
  {
  }

  public ElementOperationFailedExceptionHolder (com.Metaswitch.MVS.Corba.ElementOperationFailedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ElementOperationFailedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ElementOperationFailedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ElementOperationFailedExceptionHelper.type ();
  }

}
