package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/ElementNotLockedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The unlock request failed because the SE is not locked by this user.
 */
public final class ElementNotLockedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public ElementNotLockedException ()
  {
    super(ElementNotLockedExceptionHelper.id());
  } // ctor

  public ElementNotLockedException (String _nlsText, String _wideNlsText)
  {
    super(ElementNotLockedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public ElementNotLockedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(ElementNotLockedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class ElementNotLockedException
