package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ElementAlreadyLockedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The lock request failed because the SE is already locked by this user.
 */
public final class ElementAlreadyLockedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.ElementAlreadyLockedException value = null;

  public ElementAlreadyLockedExceptionHolder ()
  {
  }

  public ElementAlreadyLockedExceptionHolder (com.Metaswitch.MVS.Corba.ElementAlreadyLockedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ElementAlreadyLockedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ElementAlreadyLockedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ElementAlreadyLockedExceptionHelper.type ();
  }

}
