package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ElementOrderHintValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class ElementOrderHintValueHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.ElementOrderHintValue value = null;

  public ElementOrderHintValueHolder ()
  {
  }

  public ElementOrderHintValueHolder (com.Metaswitch.MVS.Corba.ElementOrderHintValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.type ();
  }

}
