package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/FieldNoRegisteredPVPException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown by the "possible values" methods on the SettingsUserInterface
 * if the field does not have a PossibleValuesProvider.  If the
 * hasPossibleValues method returns true then this exception will not be
 * thrown.
 */
public final class FieldNoRegisteredPVPException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public FieldNoRegisteredPVPException ()
  {
    super(FieldNoRegisteredPVPExceptionHelper.id());
  } // ctor

  public FieldNoRegisteredPVPException (String _nlsText, String _wideNlsText)
  {
    super(FieldNoRegisteredPVPExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public FieldNoRegisteredPVPException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(FieldNoRegisteredPVPExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class FieldNoRegisteredPVPException
