package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/FieldNoRegisteredAPExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown by the "get adjustmnents" methods on the SettingsUserInterface
 * if the field does not have an AdjustmentsProvider.  If the
 * hasAdjustments method returns true then this exception will not be
 * thrown.
 */
public final class FieldNoRegisteredAPExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.FieldNoRegisteredAPException value = null;

  public FieldNoRegisteredAPExceptionHolder ()
  {
  }

  public FieldNoRegisteredAPExceptionHolder (com.Metaswitch.MVS.Corba.FieldNoRegisteredAPException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.FieldNoRegisteredAPExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.FieldNoRegisteredAPExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.FieldNoRegisteredAPExceptionHelper.type ();
  }

}
