package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/FieldNameOrIndexNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the fieldName or fieldIndex value passed on a
 * SettingsUserInterface method invocation does not refer to a valid field.
 */
public final class FieldNameOrIndexNotFoundException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public FieldNameOrIndexNotFoundException ()
  {
    super(FieldNameOrIndexNotFoundExceptionHelper.id());
  } // ctor

  public FieldNameOrIndexNotFoundException (String _nlsText, String _wideNlsText)
  {
    super(FieldNameOrIndexNotFoundExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public FieldNameOrIndexNotFoundException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(FieldNameOrIndexNotFoundExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class FieldNameOrIndexNotFoundException
