package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/FieldNoRegisteredPVPExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown by the "possible values" methods on the SettingsUserInterface
 * if the field does not have a PossibleValuesProvider.  If the
 * hasPossibleValues method returns true then this exception will not be
 * thrown.
 */
public final class FieldNoRegisteredPVPExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.FieldNoRegisteredPVPException value = null;

  public FieldNoRegisteredPVPExceptionHolder ()
  {
  }

  public FieldNoRegisteredPVPExceptionHolder (com.Metaswitch.MVS.Corba.FieldNoRegisteredPVPException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.FieldNoRegisteredPVPExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.FieldNoRegisteredPVPExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.FieldNoRegisteredPVPExceptionHelper.type ();
  }

}
