package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/FieldBadValueException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if a method invocation attempts to set a field with a value that is
 * not valid.  The nlsText string details why the value is not valid.
 */
public final class FieldBadValueException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public FieldBadValueException ()
  {
    super(FieldBadValueExceptionHelper.id());
  } // ctor

  public FieldBadValueException (String _nlsText, String _wideNlsText)
  {
    super(FieldBadValueExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public FieldBadValueException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(FieldBadValueExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class FieldBadValueException
