package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/InvalidNameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The supplied SE name is not a valid name.  This does not mean that the
 * SE does not exist.  Rather that the structure of the name is not valid.
 */
public final class InvalidNameException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public InvalidNameException ()
  {
    super(InvalidNameExceptionHelper.id());
  } // ctor

  public InvalidNameException (String _nlsText, String _wideNlsText)
  {
    super(InvalidNameExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public InvalidNameException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(InvalidNameExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class InvalidNameException
