package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/InvalidFilterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The supplied filter is not valid.  See comments on individual methods that
 * declare this exception.
 */
public final class InvalidFilterException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public InvalidFilterException ()
  {
    super(InvalidFilterExceptionHelper.id());
  } // ctor

  public InvalidFilterException (String _nlsText, String _wideNlsText)
  {
    super(InvalidFilterExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public InvalidFilterException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(InvalidFilterExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class InvalidFilterException
