package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/LockTimeoutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * Thrown if the SE's lock which was previously obtained by invoking the lock
 * method has expired.  SE locks expire/timeout after a fixed period of 30
 * seconds.  Those methods that declare the LockTimeoutException
 * will not throw this exception if the lock method has not been explicitly
 * called by the SEAccessInterface user.
 */
public final class LockTimeoutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.LockTimeoutException value = null;

  public LockTimeoutExceptionHolder ()
  {
  }

  public LockTimeoutExceptionHolder (com.Metaswitch.MVS.Corba.LockTimeoutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.LockTimeoutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.LockTimeoutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.LockTimeoutExceptionHelper.type ();
  }

}
