package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/LockTimeoutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * Thrown if the SE's lock which was previously obtained by invoking the lock
 * method has expired.  SE locks expire/timeout after a fixed period of 30
 * seconds.  Those methods that declare the LockTimeoutException
 * will not throw this exception if the lock method has not been explicitly
 * called by the SEAccessInterface user.
 */
public final class LockTimeoutException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public LockTimeoutException ()
  {
    super(LockTimeoutExceptionHelper.id());
  } // ctor

  public LockTimeoutException (String _nlsText, String _wideNlsText)
  {
    super(LockTimeoutExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public LockTimeoutException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(LockTimeoutExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class LockTimeoutException
