package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/LogInformationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/

abstract public class LogInformationHelper
{
  private static String  _id = "IDL:LogInformation:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.LogInformation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.LogInformation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [17];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "severity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "acknowledged",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "suppressed",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "ruleApplied",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "node",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "logSource",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "objectName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "relatedObjects",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "description",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[10] = new org.omg.CORBA.StructMember (
            "cause",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[11] = new org.omg.CORBA.StructMember (
            "effect",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[12] = new org.omg.CORBA.StructMember (
            "action",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[13] = new org.omg.CORBA.StructMember (
            "userComments",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[14] = new org.omg.CORBA.StructMember (
            "associatedLogCorrelator",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[15] = new org.omg.CORBA.StructMember (
            "associatedNodeName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[16] = new org.omg.CORBA.StructMember (
            "associatedNodeUID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.Metaswitch.MVS.Corba.LogInformationHelper.id (), "LogInformation", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.LogInformation read (org.omg.CORBA.portable.InputStream istream)
  {
    com.Metaswitch.MVS.Corba.LogInformation value = new com.Metaswitch.MVS.Corba.LogInformation ();
    value.time = istream.read_longlong ();
    value.severity = istream.read_long ();
    value.acknowledged = istream.read_boolean ();
    value.suppressed = istream.read_boolean ();
    value.ruleApplied = istream.read_boolean ();
    value.node = istream.read_string ();
    value.logSource = istream.read_string ();
    value.objectName = istream.read_string ();
    value.relatedObjects = istream.read_string ();
    value.description = istream.read_string ();
    value.cause = istream.read_string ();
    value.effect = istream.read_string ();
    value.action = istream.read_string ();
    value.userComments = istream.read_string ();
    value.associatedLogCorrelator = istream.read_longlong ();
    value.associatedNodeName = istream.read_string ();
    value.associatedNodeUID = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.LogInformation value)
  {
    ostream.write_longlong (value.time);
    ostream.write_long (value.severity);
    ostream.write_boolean (value.acknowledged);
    ostream.write_boolean (value.suppressed);
    ostream.write_boolean (value.ruleApplied);
    ostream.write_string (value.node);
    ostream.write_string (value.logSource);
    ostream.write_string (value.objectName);
    ostream.write_string (value.relatedObjects);
    ostream.write_string (value.description);
    ostream.write_string (value.cause);
    ostream.write_string (value.effect);
    ostream.write_string (value.action);
    ostream.write_string (value.userComments);
    ostream.write_longlong (value.associatedLogCorrelator);
    ostream.write_string (value.associatedNodeName);
    ostream.write_string (value.associatedNodeUID);
  }

}
