package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/LoginFailedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if login fails.  The nlsText field details why the login failed.
 */
public final class LoginFailedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public LoginFailedException ()
  {
    super(LoginFailedExceptionHelper.id());
  } // ctor

  public LoginFailedException (String _nlsText, String _wideNlsText)
  {
    super(LoginFailedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public LoginFailedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(LoginFailedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class LoginFailedException
