package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/LogNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * A log matching the specified correlator and MetaSwitch identifier could
 * not be found.  Reasons for this include:
 * - the log has not yet been retreived from the MetaSwitch,
 * - the log has been retreived from the MetaSwitch, but has since been
 *   deleted,
 * - the log has been filtered out,
 * - the EMS log storage facility is not currently available,
 * - the ClientSession has expired.
 */
public final class LogNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.LogNotFoundException value = null;

  public LogNotFoundExceptionHolder ()
  {
  }

  public LogNotFoundExceptionHolder (com.Metaswitch.MVS.Corba.LogNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.LogNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.LogNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.LogNotFoundExceptionHelper.type ();
  }

}
