package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/NameUnknownExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The SE's name is not known because the SE has not been fully created.
 * This is the case after an attachToNew, before the first successful
 * doAction(APPLY).
 */
public final class NameUnknownExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.NameUnknownException value = null;

  public NameUnknownExceptionHolder ()
  {
  }

  public NameUnknownExceptionHolder (com.Metaswitch.MVS.Corba.NameUnknownException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.NameUnknownExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.NameUnknownExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.NameUnknownExceptionHelper.type ();
  }

}
