package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/NLSLocale.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NLSSupportInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class NLSLocale implements org.omg.CORBA.portable.IDLEntity
{

  /**
     * Idenifier of the specific NLS Locale.  This string is interpretable only
     * by the EMS Server and is read only.
     */
  public String localeIdentifier = null;

  public NLSLocale ()
  {
  } // ctor

  public NLSLocale (String _localeIdentifier)
  {
    localeIdentifier = _localeIdentifier;
  } // ctor

} // class NLSLocale
