package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/NLSLocaleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NLSSupportInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

abstract public class NLSLocaleHelper
{
  private static String  _id = "IDL:NLSLocale:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.NLSLocale that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.NLSLocale extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "localeIdentifier",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.Metaswitch.MVS.Corba.NLSLocaleHelper.id (), "NLSLocale", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.NLSLocale read (org.omg.CORBA.portable.InputStream istream)
  {
    com.Metaswitch.MVS.Corba.NLSLocale value = new com.Metaswitch.MVS.Corba.NLSLocale ();
    value.localeIdentifier = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.NLSLocale value)
  {
    ostream.write_string (value.localeIdentifier);
  }

}
