package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/NLSLocaleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NLSSupportInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class NLSLocaleHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.NLSLocale value = null;

  public NLSLocaleHolder ()
  {
  }

  public NLSLocaleHolder (com.Metaswitch.MVS.Corba.NLSLocale initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.NLSLocaleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.NLSLocaleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.NLSLocaleHelper.type ();
  }

}
