package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/NLSSupportInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NLSSupportInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The NLSSupportInterface provides translation from National Language Support
 * (NLS) enabled text into human-readable displayable text.
 */
public final class NLSSupportInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.NLSSupportInterface value = null;

  public NLSSupportInterfaceHolder ()
  {
  }

  public NLSSupportInterfaceHolder (com.Metaswitch.MVS.Corba.NLSSupportInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.NLSSupportInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.NLSSupportInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.NLSSupportInterfaceHelper.type ();
  }

}
