package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/NLSSupportInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NLSSupportInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The NLSSupportInterface provides translation from National Language Support
 * (NLS) enabled text into human-readable displayable text.
 */
public interface NLSSupportInterface extends NLSSupportInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  /**
      * Resource type identifier used on the makeDisplayTextFromLogID[WithParams]
      * methods to request the log "Severity" information.
      */
  public static final int NLS_LOG_LEVEL = (int)(2);

  /**
      * Resource type identifier used on the makeDisplayTextFromLogID[WithParams]
      * methods to request the log "Cause" information.
      */
  public static final int NLS_LOG_CAUSE = (int)(3);

  /**
      * Resource type identifier used on the makeDisplayTextFromLogID[WithParams]
      * methods to request the log "Effect" information.
      */
  public static final int NLS_LOG_EFFECT = (int)(4);

  /**
      * Resource type identifier used on the makeDisplayTextFromLogID[WithParams]
      * methods to request the log "Action" information.
      */
  public static final int NLS_LOG_ACTION = (int)(5);

  /**
      * Resource type identifier used on the makeDisplayTextFromLogID[WithParams]
      * methods to request the log "Description" information.
      */
  public static final int NLS_LOG_DESCRIPTION = (int)(6);
} // interface NLSSupportInterface
