package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/NoSnapshotChangeListenersExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown on a removeSnapshotChangeListener request if no interface is
 * currently registered as listening.
 */
public final class NoSnapshotChangeListenersExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.NoSnapshotChangeListenersException value = null;

  public NoSnapshotChangeListenersExceptionHolder ()
  {
  }

  public NoSnapshotChangeListenersExceptionHolder (com.Metaswitch.MVS.Corba.NoSnapshotChangeListenersException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.NoSnapshotChangeListenersExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.NoSnapshotChangeListenersExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.NoSnapshotChangeListenersExceptionHelper.type ();
  }

}
