package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/NotAttachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The request failed because the SEAccessInterface must be attached to an SE
 * to perform this operation.
 */
public final class NotAttachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.NotAttachedException value = null;

  public NotAttachedExceptionHolder ()
  {
  }

  public NotAttachedExceptionHolder (com.Metaswitch.MVS.Corba.NotAttachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.NotAttachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.NotAttachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.NotAttachedExceptionHelper.type ();
  }

}
