package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/NotAttachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The request failed because the SEAccessInterface must be attached to an SE
 * to perform this operation.
 */
public final class NotAttachedException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public NotAttachedException ()
  {
    super(NotAttachedExceptionHelper.id());
  } // ctor

  public NotAttachedException (String _nlsText, String _wideNlsText)
  {
    super(NotAttachedExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public NotAttachedException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(NotAttachedExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class NotAttachedException
