package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/omlapiHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from omlapi.idl
* Thursday, June 18, 2020 8:33:06 PM CDT
*/


//-----------------------------------------------------------------------------
public final class omlapiHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.omlapi value = null;

  public omlapiHolder ()
  {
  }

  public omlapiHolder (com.Metaswitch.MVS.Corba.omlapi initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.omlapiHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.omlapiHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.omlapiHelper.type ();
  }

}
