package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/omlapiHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from omlapi.idl
* Thursday, June 18, 2020 8:33:06 PM CDT
*/


//-----------------------------------------------------------------------------
abstract public class omlapiHelper
{
  private static String  _id = "IDL:omlapi:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.omlapi that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.omlapi extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.Metaswitch.MVS.Corba.omlapiHelper.id (), "omlapi");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.omlapi read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_omlapiStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.omlapi value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.Metaswitch.MVS.Corba.omlapi narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.omlapi)
      return (com.Metaswitch.MVS.Corba.omlapi)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._omlapiStub stub = new com.Metaswitch.MVS.Corba._omlapiStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.Metaswitch.MVS.Corba.omlapi unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.Metaswitch.MVS.Corba.omlapi)
      return (com.Metaswitch.MVS.Corba.omlapi)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.Metaswitch.MVS.Corba._omlapiStub stub = new com.Metaswitch.MVS.Corba._omlapiStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
