package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/ReadWriteSettingsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if an error occurs serializing or deserializing a
 * SettingsUserInterface object.
 */
public final class ReadWriteSettingsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.ReadWriteSettingsException value = null;

  public ReadWriteSettingsExceptionHolder ()
  {
  }

  public ReadWriteSettingsExceptionHolder (com.Metaswitch.MVS.Corba.ReadWriteSettingsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.ReadWriteSettingsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.ReadWriteSettingsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.ReadWriteSettingsExceptionHelper.type ();
  }

}
