package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/SEAccessInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * The SEAccessInterface is the primary interface for navigating the tree of
 * SE objects and managing individual SEs.
 */
public final class SEAccessInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.SEAccessInterface value = null;

  public SEAccessInterfaceHolder ()
  {
  }

  public SEAccessInterfaceHolder (com.Metaswitch.MVS.Corba.SEAccessInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SEAccessInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SEAccessInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SEAccessInterfaceHelper.type ();
  }

}
