package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class SEAction implements org.omg.CORBA.portable.IDLEntity
{
  public int actionID = (int)0;
  public boolean actionRequiresSettings = false;
  public long accessFlagsByGroup = (long)0;
  public int currentAccessPermissions = (int)0;
  public int confirmationNLSIID = (int)0;
  public int actionImpactFlags = (int)0;

  public SEAction ()
  {
  } // ctor

  public SEAction (int _actionID, boolean _actionRequiresSettings, long _accessFlagsByGroup, int _currentAccessPermissions, int _confirmationNLSIID, int _actionImpactFlags)
  {
    actionID = _actionID;
    actionRequiresSettings = _actionRequiresSettings;
    accessFlagsByGroup = _accessFlagsByGroup;
    currentAccessPermissions = _currentAccessPermissions;
    confirmationNLSIID = _confirmationNLSIID;
    actionImpactFlags = _actionImpactFlags;
  } // ctor

} // class SEAction
