package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEAccessFactoryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessFactoryInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/

public interface SEAccessFactoryInterface extends SEAccessFactoryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SEAccessFactoryInterface
