package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/SEAccessFactoryInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessFactoryInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/

public final class SEAccessFactoryInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.SEAccessFactoryInterface value = null;

  public SEAccessFactoryInterfaceHolder ()
  {
  }

  public SEAccessFactoryInterfaceHolder (com.Metaswitch.MVS.Corba.SEAccessFactoryInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SEAccessFactoryInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SEAccessFactoryInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SEAccessFactoryInterfaceHelper.type ();
  }

}
