package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEAccessFactoryInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessFactoryInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/

public interface SEAccessFactoryInterfaceOperations 
{

  /**
     * Each invocation of createsSEAccess returns an identical, generic
     * SEAccessInterface instance; this instance only becomes associated with a
     * specific SE as a result of subsequent method invocations on the
     * SEAccessInterface.  The client application is obliged to call the destroy
     * method on the SEAccessInterface when it has finished using it.
     *
     * @return SEAccessInterface instance.
     *
     * @throws ElementOperationFailedException  If the request failed for any
     *   reason, for example if the EMS Server does not have enough memory to
     *   complete the request.  See SEExceptions.idl.
     */
  com.Metaswitch.MVS.Corba.SEAccessInterface createSEAccess () throws com.Metaswitch.MVS.Corba.ElementOperationFailedException;
} // interface SEAccessFactoryInterfaceOperations
