package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEExceptionsInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


//-----------------------------------------------------------------------------
public interface SEExceptionsInterfaceOperations 
{
} // interface SEExceptionsInterfaceOperations
