package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEProperties.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

public final class SEProperties implements org.omg.CORBA.portable.IDLEntity
{
  public int version = (int)0;
  public String elementType = null;
  public String displayType = null;
  public String parentType = null;
  public com.Metaswitch.MVS.Corba.SEAction allActions[] = null;
  public com.Metaswitch.MVS.Corba.SEChildProperties childProperties[] = null;
  public long accessFlagsByGroup = (long)0;
  public int currentAccessPermissions = (int)0;
  public com.Metaswitch.MVS.Corba.ElementOrderHintValue elementOrderHint = null;
  public int typeFlags = (int)0;

  public SEProperties ()
  {
  } // ctor

  public SEProperties (int _version, String _elementType, String _displayType, String _parentType, com.Metaswitch.MVS.Corba.SEAction[] _allActions, com.Metaswitch.MVS.Corba.SEChildProperties[] _childProperties, long _accessFlagsByGroup, int _currentAccessPermissions, com.Metaswitch.MVS.Corba.ElementOrderHintValue _elementOrderHint, int _typeFlags)
  {
    version = _version;
    elementType = _elementType;
    displayType = _displayType;
    parentType = _parentType;
    allActions = _allActions;
    childProperties = _childProperties;
    accessFlagsByGroup = _accessFlagsByGroup;
    currentAccessPermissions = _currentAccessPermissions;
    elementOrderHint = _elementOrderHint;
    typeFlags = _typeFlags;
  } // ctor

} // class SEProperties
