package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SEPropertiesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/

abstract public class SEPropertiesHelper
{
  private static String  _id = "IDL:SEProperties:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.SEProperties that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.SEProperties extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [10];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "version",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "elementType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "displayType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "parentType",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.Metaswitch.MVS.Corba.SEActionHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.Metaswitch.MVS.Corba.SequenceOfSEActionsHelper.id (), "SequenceOfSEActions", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "allActions",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.Metaswitch.MVS.Corba.SEChildPropertiesHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.Metaswitch.MVS.Corba.SequenceOfSEChildPropertiesHelper.id (), "SequenceOfSEChildProperties", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "childProperties",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[6] = new org.omg.CORBA.StructMember (
            "accessFlagsByGroup",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "currentAccessPermissions",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.type ();
          _members0[8] = new org.omg.CORBA.StructMember (
            "elementOrderHint",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[9] = new org.omg.CORBA.StructMember (
            "typeFlags",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.Metaswitch.MVS.Corba.SEPropertiesHelper.id (), "SEProperties", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.SEProperties read (org.omg.CORBA.portable.InputStream istream)
  {
    com.Metaswitch.MVS.Corba.SEProperties value = new com.Metaswitch.MVS.Corba.SEProperties ();
    value.version = istream.read_long ();
    value.elementType = istream.read_string ();
    value.displayType = istream.read_string ();
    value.parentType = istream.read_string ();
    value.allActions = com.Metaswitch.MVS.Corba.SequenceOfSEActionsHelper.read (istream);
    value.childProperties = com.Metaswitch.MVS.Corba.SequenceOfSEChildPropertiesHelper.read (istream);
    value.accessFlagsByGroup = istream.read_longlong ();
    value.currentAccessPermissions = istream.read_long ();
    value.elementOrderHint = com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.read (istream);
    value.typeFlags = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.SEProperties value)
  {
    ostream.write_long (value.version);
    ostream.write_string (value.elementType);
    ostream.write_string (value.displayType);
    ostream.write_string (value.parentType);
    com.Metaswitch.MVS.Corba.SequenceOfSEActionsHelper.write (ostream, value.allActions);
    com.Metaswitch.MVS.Corba.SequenceOfSEChildPropertiesHelper.write (ostream, value.childProperties);
    ostream.write_longlong (value.accessFlagsByGroup);
    ostream.write_long (value.currentAccessPermissions);
    com.Metaswitch.MVS.Corba.ElementOrderHintValueHelper.write (ostream, value.elementOrderHint);
    ostream.write_long (value.typeFlags);
  }

}
