package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SequenceOfIndicesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SettingsUserInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Define SequenceOfIndices to be a sequence of strings to hold all forms
 * of index value.  We use this because we want an unbounded number of
 * strings - an IDL sequence is unbounded, but an array is not.
 **/
public final class SequenceOfIndicesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public SequenceOfIndicesHolder ()
  {
  }

  public SequenceOfIndicesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SequenceOfIndicesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SequenceOfIndicesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SequenceOfIndicesHelper.type ();
  }

}
