package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SequenceOfReferencesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * A sequence of Reference objects.
 */
public final class SequenceOfReferencesHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.Reference value[] = null;

  public SequenceOfReferencesHolder ()
  {
  }

  public SequenceOfReferencesHolder (com.Metaswitch.MVS.Corba.Reference[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SequenceOfReferencesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SequenceOfReferencesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SequenceOfReferencesHelper.type ();
  }

}
