package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SequenceOfSEChildPropertiesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEAccessInterface.idl
* Thursday, June 18, 2020 8:33:02 PM CDT
*/


/**
 * Define SequenceOfSEChildProperties to be a sequence of SEChildProperties
 * objects. We use this because we want an unbounded number of SEActions - an
 * IDL sequence is unbounded, but an array is not.
 */
abstract public class SequenceOfSEChildPropertiesHelper
{
  private static String  _id = "IDL:SequenceOfSEChildProperties:1.0";

  public static void insert (org.omg.CORBA.Any a, com.Metaswitch.MVS.Corba.SEChildProperties[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.Metaswitch.MVS.Corba.SEChildProperties[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.Metaswitch.MVS.Corba.SEChildPropertiesHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.Metaswitch.MVS.Corba.SequenceOfSEChildPropertiesHelper.id (), "SequenceOfSEChildProperties", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.Metaswitch.MVS.Corba.SEChildProperties[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.Metaswitch.MVS.Corba.SEChildProperties value[] = null;
    int _len0 = istream.read_long ();
    value = new com.Metaswitch.MVS.Corba.SEChildProperties[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.Metaswitch.MVS.Corba.SEChildPropertiesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.Metaswitch.MVS.Corba.SEChildProperties[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.Metaswitch.MVS.Corba.SEChildPropertiesHelper.write (ostream, value[_i0]);
  }

}
