package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SequenceOfIntegersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SettingsUserInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Define SequenceOfIntegers to be a sequence of 32-bit integers.
 * We use this to provide an unbounded number of integers.
 **/
public final class SequenceOfIntegersHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public SequenceOfIntegersHolder ()
  {
  }

  public SequenceOfIntegersHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SequenceOfIntegersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SequenceOfIntegersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SequenceOfIntegersHelper.type ();
  }

}
