package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/SettingsUserInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SettingsUserInterface.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The SettingsUserInterface provides the client application with methods to:
 * enumerate fields; obtain detailed type information that describes each of
 * the fields including ranges, units and default values; get and set field
 * values; query lists of possible values for fields.
 */
public final class SettingsUserInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.SettingsUserInterface value = null;

  public SettingsUserInterfaceHolder ()
  {
  }

  public SettingsUserInterfaceHolder (com.Metaswitch.MVS.Corba.SettingsUserInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SettingsUserInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SettingsUserInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SettingsUserInterfaceHelper.type ();
  }

}
