package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/SnapshotChangeListenerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SnapshotChangeListenerInterface.idl
* Thursday, June 18, 2020 8:33:05 PM CDT
*/

public final class SnapshotChangeListenerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.SnapshotChangeListenerInterface value = null;

  public SnapshotChangeListenerInterfaceHolder ()
  {
  }

  public SnapshotChangeListenerInterfaceHolder (com.Metaswitch.MVS.Corba.SnapshotChangeListenerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.SnapshotChangeListenerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.SnapshotChangeListenerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.SnapshotChangeListenerInterfaceHelper.type ();
  }

}
