package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SnapshotChangeListenerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SnapshotChangeListenerInterface.idl
* Thursday, June 18, 2020 8:33:05 PM CDT
*/

public interface SnapshotChangeListenerInterface extends SnapshotChangeListenerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SnapshotChangeListenerInterface
