package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SUPPORT_EXACT_SINGLE_VERSION.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionManagerInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/

public interface SUPPORT_EXACT_SINGLE_VERSION
{
  public static final int value = (int)(3);
}
