package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/SUPPORT_RANGE_OF_VERSIONS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientSessionManagerInterface.idl
* Thursday, June 18, 2020 8:33:04 PM CDT
*/

public interface SUPPORT_RANGE_OF_VERSIONS
{
  public static final int value = (int)(2);
}
