package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/TooManySnapshotChangeListenersExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown on an addSnapshotChangeListener request if an interface is already
 * registered as listening. Only one SnapshotChangeListener is allowed.
 */
public final class TooManySnapshotChangeListenersExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.TooManySnapshotChangeListenersException value = null;

  public TooManySnapshotChangeListenersExceptionHolder ()
  {
  }

  public TooManySnapshotChangeListenersExceptionHolder (com.Metaswitch.MVS.Corba.TooManySnapshotChangeListenersException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.TooManySnapshotChangeListenersExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.TooManySnapshotChangeListenersExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.TooManySnapshotChangeListenersExceptionHelper.type ();
  }

}
