package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/UnknownActionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * The specified action is not supported by this SE under any circumstance.
 * All supported actions are listed in the SEProperties object returned on
 * attachment.
 */
public final class UnknownActionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.UnknownActionException value = null;

  public UnknownActionExceptionHolder ()
  {
  }

  public UnknownActionExceptionHolder (com.Metaswitch.MVS.Corba.UnknownActionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.UnknownActionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.UnknownActionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.UnknownActionExceptionHelper.type ();
  }

}
