package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/UnrecognizedNLSIIDExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the NLSIID supplied to the makeDisplayText method is not an
 * NLS key recognized by the EMS Server.  All NLSIIDs returned by the EMS
 * Server are recognized so if the interface it adhered to this is an
 * assertable condition.
 */
public final class UnrecognizedNLSIIDExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.UnrecognizedNLSIIDException value = null;

  public UnrecognizedNLSIIDExceptionHolder ()
  {
  }

  public UnrecognizedNLSIIDExceptionHolder (com.Metaswitch.MVS.Corba.UnrecognizedNLSIIDException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.UnrecognizedNLSIIDExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.UnrecognizedNLSIIDExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.UnrecognizedNLSIIDExceptionHelper.type ();
  }

}
