package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/UnrecognizedNLSIIDException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the NLSIID supplied to the makeDisplayText method is not an
 * NLS key recognized by the EMS Server.  All NLSIIDs returned by the EMS
 * Server are recognized so if the interface it adhered to this is an
 * assertable condition.
 */
public final class UnrecognizedNLSIIDException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public UnrecognizedNLSIIDException ()
  {
    super(UnrecognizedNLSIIDExceptionHelper.id());
  } // ctor

  public UnrecognizedNLSIIDException (String _nlsText, String _wideNlsText)
  {
    super(UnrecognizedNLSIIDExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public UnrecognizedNLSIIDException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(UnrecognizedNLSIIDExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class UnrecognizedNLSIIDException
