package com.Metaswitch.MVS.Corba;


/**
* com/Metaswitch/MVS/Corba/UnsupportedLocaleException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the supplied country and language codes do not form a recognized
 * Locale for which the EMS Server has National Language Support.  For example,
 * if "FR" & "fr" are passed to an EMS Server that does not support NLS
 * translation to French then this exception is thrown.
 */
public final class UnsupportedLocaleException extends org.omg.CORBA.UserException
{
  public String nlsText = null;
  public String wideNlsText = null;

  public UnsupportedLocaleException ()
  {
    super(UnsupportedLocaleExceptionHelper.id());
  } // ctor

  public UnsupportedLocaleException (String _nlsText, String _wideNlsText)
  {
    super(UnsupportedLocaleExceptionHelper.id());
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor


  public UnsupportedLocaleException (String $reason, String _nlsText, String _wideNlsText)
  {
    super(UnsupportedLocaleExceptionHelper.id() + "  " + $reason);
    nlsText = _nlsText;
    wideNlsText = _wideNlsText;
  } // ctor

} // class UnsupportedLocaleException
