package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/UnsupportedLocaleExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the supplied country and language codes do not form a recognized
 * Locale for which the EMS Server has National Language Support.  For example,
 * if "FR" & "fr" are passed to an EMS Server that does not support NLS
 * translation to French then this exception is thrown.
 */
public final class UnsupportedLocaleExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.UnsupportedLocaleException value = null;

  public UnsupportedLocaleExceptionHolder ()
  {
  }

  public UnsupportedLocaleExceptionHolder (com.Metaswitch.MVS.Corba.UnsupportedLocaleException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.UnsupportedLocaleExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.UnsupportedLocaleExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.UnsupportedLocaleExceptionHelper.type ();
  }

}
