package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/VersionNotSupportedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the range of EMS object versions, specified by the
 * lowestSuppliedVersion and highestSuppliedVersion parameters on the
 * ClientSessionManager login methods, does not overlap with the range of EMS
 * object versions supported by the EMS.
 */
public final class VersionNotSupportedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.VersionNotSupportedException value = null;

  public VersionNotSupportedExceptionHolder ()
  {
  }

  public VersionNotSupportedExceptionHolder (com.Metaswitch.MVS.Corba.VersionNotSupportedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.VersionNotSupportedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.VersionNotSupportedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.VersionNotSupportedExceptionHelper.type ();
  }

}
