package com.Metaswitch.MVS.Corba;

/**
* com/Metaswitch/MVS/Corba/VersionFormatExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SEExceptions.idl
* Thursday, June 18, 2020 8:33:03 PM CDT
*/


/**
 * Thrown if the format of a version identifier is not as expected.  See the
 * ClientSessionManagerInterface login methods for more information.
 */
public final class VersionFormatExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.Metaswitch.MVS.Corba.VersionFormatException value = null;

  public VersionFormatExceptionHolder ()
  {
  }

  public VersionFormatExceptionHolder (com.Metaswitch.MVS.Corba.VersionFormatException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.Metaswitch.MVS.Corba.VersionFormatExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.Metaswitch.MVS.Corba.VersionFormatExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.Metaswitch.MVS.Corba.VersionFormatExceptionHelper.type ();
  }

}
